---
title: "STA303H1S/1002H Module 3"
subtitle: "Class code demo"
author: "Prof. Liza Bolton"
date: "February 09, 2022"
output:
  pdf_document: default
---

> *I grow rows and rows of roses*
> *Flor de mayo, by the mile*


# Useful shortcuts in RStudio

[Link](https://bookdown.org/yihui/rmarkdown-cookbook/rstudio-shortcuts.html)

# Rose farm

There are 5 greenhouses on your rose farm, North, East, South, West and Central. They are at different levels of modernization as it can be very expensive to replace and update irrigation systems and other fixtures. You hope to be making some general improvements.

THere are 4 varieties of red rose that your farm specilizes in: Devotion, Checkmate, Wanted, and Hearts.

Within each greenhouse, there are 32 plots. In prepration for the 2021 Valentine's Day, you planted equal plots of each of the special varieties in each greenhouse. Then the flowers were cut and sold and it was recorded how much net profit was made per plot.

Now, you want to understand your data from last year and make predictions about your 2022 profits. (Ignoring inflation, which probably shouldn't do, eh? Yikes. The economy, amirite?)

## Grow roses

This setup chunk load the function that will 'grow' our roses (and profit data) for us. For this class demo, we will all have the same rose data, but you will have different data to your peers in the portfolio.

We don't really need to do the seed set up and everythinh here, but I wanted to give you a useful example for your portfolio. Be very careful about relative paths to files. MarkUs autograding will be set up based on the same structure as the JupyterHub and will require relative paths


## Teaching and learning world

- Using LM
- Can ONLY do this for balanced designs


## Real world
